all:
  children:
    admin_servers:
      hosts:
        <YOUR IP HERE>:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/<YOUR SSH KEY HERE>
          ansible_connection: ssh
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o PreferredAuthentications=publickey'
