- name: Install Python build dependencies
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - tar
      - bzip2
      - bzip2-devel
      - libffi-devel
      - zlib-devel
      - xz-devel
      - openssl-devel
      - ncurses-devel
      - readline-devel
      - wget
      - findutils
    state: present
  tags:
    - install-python

- name: Download Python source
  get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "/{{ tmp_dir }}/Python-{{ python_version }}.tgz"
    mode: '0644'
  tags:
    - install-python

- name: Extract Python source to tmp dir
  unarchive:
    src: "/{{ tmp_dir }}/Python-{{ python_version }}.tgz"
    dest: "/{{ tmp_dir }}"
    remote_src: yes
  tags:
    - install-python

- name: Compile and install Python
  shell: |
    cd /{{ tmp_dir }}/Python-{{ python_version }}
    ./configure --enable-optimizations --prefix={{ python_prefix }}
    make -j "$(nproc)"
    make altinstall
  args:
    creates: "{{ python_prefix }}/bin/python{{ python_major_version }}"
  tags:
    - install-python

- name: Symlink Python system-wide as {{ python_link_name }}
  ansible.builtin.file:
    src: "{{ python_prefix }}/bin/python{{ python_major_version }}"
    dest: "/usr/bin/{{ python_link_name }}"
    state: link
    force: true
  tags:
    - install-python

- name: Verify Python installation
  command: "{{ python_link_name }} --version"
  register: python_version_output
  tags:
    - install-python

- name: Print installed Python version
  debug:
    msg: "Installed Python version: {{ python_version_output.stdout }}"
  tags:
    - install-python

- name: Clean up extracted source directory
  file:
    path: "/{{ tmp_dir }}/Python-{{ python_version }}"
    state: absent
  tags:
    - install-python

- name: Clean up downloaded archive
  file:
    path: "/{{ tmp_dir }}/Python-{{ python_version }}.tgz"
    state: absent
  tags:
    - install-python

